[tool.bumper]
current_version = "0.2.0"
versioning_type = "semver"

[[tool.bumper.files]]
file = "./pyproject.toml"
search = 'version = "{current_version}"'

[[tool.bumper.files]]
file = "./README.md"
search = "flake8-define-class-attributes/{current_version}"

[[tool.bumper.files]]
file = "./README.md"
search = "flake8-define-class-attributes: {current_version},"

[[tool.bumper.files]]
file = "./flake8_define_class_attributes/__init__.py"
search = '__version__ = "{current_version}"'
